<?
/**
 * @var int             $id
 * @var string          $title
 * @var \product_item[] $products
 */
?>
<div id="<?= $id ?>" class="filter-products-wrapper mb30">
    <div class="filter-products-title"><?= $title ?></div>
    <div class="owl-carousel owl-theme owl-filter-product">
        <? foreach ($products as $key => $product) { ?>
            <div class="item">
                <div class="product-list">
                    <div class="product-wrapper">
                        <?= $product->generate() ?>
                    </div><!-- #product-wrapper# -->
                </div><!-- #product-list# -->
            </div><!-- #item# -->
        <? } ?>
    </div>
</div>
<script>
    $(document).ready(function () {
        $('#<?=$id?> .owl-carousel').owlCarousel({
            itemsCustom: [
                [0, 1],
                [450, 2],
                [600, 2],
                [700, 2],
                [1000, 2],
                [1200, 4],
                [1400, 4],
                [1600, 4]
            ],
            navigation: true, // Show next and prev buttons
            slideSpeed: 300,
            paginationSpeed: 400,
            singleItem: false,
            navigationText: ['<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>',
                '<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>']

            // "singleItem:true" is a shortcut for:
            // items : 1,
            // itemsDesktop : false,
            // itemsDesktopSmall : false,
            // itemsTablet: false,
            // itemsMobile : false
        });
    });
</script>
