<?
/**
 * @var category_model[] $catalogs
 * @var category_model   $category
 */
?>
<div id="boardnav" class="toggle-menu black-blue">
    <div class="container">
        <div class="row">
            <div class="static col-md-12">
                <nav id="main-menu" class="navbar">
                    <ul class="nav navbar-nav">
                        <? if (count($catalogs)) { ?>
                            <? foreach ($catalogs as $catalog) { ?>
                                <? if (isset($childCategories[$catalog['id']]) && count($childCategories[$catalog['id']])) { ?>
                                    <li class="dropdown-opener">
                                        <a href="<?= $catalog['link'] ?>"><?= $catalog['name'] ?> <span class="caret"></span></a>
                                        <ul class="dropdown-menu">
                                            <? foreach ($childCategories[$catalog['id']] as $category) { ?>
                                                <li><a href="<?= $category['link'] ?>"><?= $category['name'] ?></a></li>
                                            <? } ?>
                                        </ul>
                                    </li>
                                <? } else { ?>
                                    <li>
                                        <a href="<?= $catalog['link'] ?>"><?= $catalog['name'] ?></a>
                                    </li>
                                <? } ?>
                            <? } ?>
                        <? } ?>
                        <li class="cart pull-right">
                            <a class="acc-btn" href="/cart">
                                <span class="glyphicon glyphicon-shopping-cart"></span>SEPETİM
                                <span class="badge cartItems pull-right"><?= session::getCartProductCount() ?></span>
                            </a>
                        </li>
                    </ul>
                </nav>
            </div><!--#col#-->
        </div><!-- #row# -->
    </div><!-- #container# -->
</div><!-- #boardnav# -->
